### PR TITLE
Implement failed tasks

### PR DESCRIPTION
**Pull request by unode**
This implements most of what was described in #55.
`status`, `cleanup`, `execute`, `graph` are also aware of failing tasks.

### CODE REVIEW

**Comment by luispedro** [comment]
This seems good. I'm going to first do a new release with `jug graph` and then merge this so that feature is out, but we keep this in testing for a while longer.

**Comment by unode** [comment]
Sounds good to me. I'm also testing it further before you merge the pull request.
It's quite a big one so I'm finding small things as I use it.
For convenience I've setup https://anaconda.org/Unode/jug with a git release that I re-upload as I find and fix issues.

With regards to `jug graph`, in case you didn't get notified, check the last comment in #58

**Comment by luispedro** [comment]
What is the general status? Are you using this?

I was wondering whether or not to start a Jug 2.0 branch where backwards compat could be broken.

**Comment by unode** [comment]
Yes I'm using it extensively. There were some quirks with the new `file_keepalive` backend but mostly works as expected.

**Comment by unode** [comment]
Last push added a small fix that would lead to accumulation of monitoring processes when several tasks failed and the options `--keep-going` and `--keep-failed` were used.

**Comment by unode** [comment]
Rebased on current master.

**Comment by unode** [comment]
Any plans to merge this? Successfully using this for close to a year.

**Comment by luispedro** [comment]
Sorry for the delay. Merged now. The next version will be 2.0.

**Pull request merged**
