### PR TITLE
Graph subcommand

### PR DESCRIPTION
**Pull request by unode**
Produce a visual representation (graph) of tasks in a jugfile.

Useful for debugging purposes and eye candy.

### CODE REVIEW

**Comment by luispedro** [comment]
Merged manually: 
https://github.com/luispedro/jug/commit/6beee8c8a7a6ac0016f32cfcea809aa6bb05fe62

**Comment by unode** [comment]
Just realized that if there are no tasks in waiting state, this doesn't actually produce a graph.
Instead it just displays unconnected nodes.

The reason is that `task.dependencies()` is empty once a task dependency is satisfied.
Can you think of any easy way to get this information once all tasks are complete?

**Comment by luispedro** [comment]
I cannot reproduce the issue with no tasks waiting.

`Task.dependencies` should not depend on the status at all (maybe there is a bug, but my recollection is that it returns the dependencies just based on the task structure).

**Comment by unode** [comment]
Just hit one.
```
Traceback (most recent call last):
  File "/data/miniconda3/envs/py3/bin/jug", line 6, in <module>
    sys.exit(jug.jug.main())
  File "/data/miniconda3/envs/py3/lib/python3.6/site-packages/jug/jug.py", line 289, in main
    cmdapi.run(options.subcommand, options=options, store=store, jugspace=jugspace)
  File "/data/miniconda3/envs/py3/lib/python3.6/site-packages/jug/subcommands/__init__.py", line 270, in run
    return cmd(*args, **kwargs)
  File "/data/miniconda3/envs/py3/lib/python3.6/site-packages/jug/subcommands/__init__.py", line 160, in __call__
    return self.run(*args, **kwargs)
  File "/data/miniconda3/envs/py3/lib/python3.6/site-packages/jug/subcommands/graph.py", line 93, in run
    targets[t.name]["deps"].add((d.name, t.name))
AttributeError: 'Tasklet' object has no attribute 'name'
```
And although unrelated I now see what the problem is.
The jugfile that failed to produce a graph makes use of `barrier()`.

**Pull request closed without merging**
