### PR TITLE
Backwards compatibility fixes

### PR DESCRIPTION
**Pull request by Unode**
`sys.argv` now contains jugfile and unparsed arguments (i.e. after `--`)
The subcommand api tests were also leaking causing other parts of the testsuite to fail.

### CODE REVIEW

**Comment by Unode** [comment]
@luispedro Please confirm that `sys.argv` works as intended now.

**Comment by luispedro** [comment]
It still didn't fix everything, but I think I now did so: https://github.com/luispedro/jug/tree/fix_sys_argv

**Comment by luispedro** [comment]
I pushed these commits + mine after rebasing onto master. Thanks!

**Comment by Unode** [comment]
Is:

    parsed = jug.options.parse(
        ["execute", "--", "--arg"])
    assert argv == ['jugfile.py', '--arg']

also supposed to be supported?

The docs also mentioned `nargs=argparse.REMAINDER` but I couldn't figure out how to make it pass for this case.

**Comment by luispedro** [comment]
Yes, that should also be supported

**Comment by luispedro** [comment]
It's not supported in the released version, so it's less important. It will not break anybody's code.

**Pull request closed without merging**
